### ISSUE TITLE
What's the difference between memKeyDB and pmem / redis?

### ISSUE THREAD

**Issue by vongosling** [memKeyDB/memKeyDB#83]
Hello, I notice that there are two pieces of code around the PMEM to help Redis adapt, and some of the code is similar[1]. Can you tell us the differences between the two solutions? Currently, we are looking for a product-based PMEM solution and hope to build it together with the community:-)

[1] https://github.com/pmem/redis

**Comment by jschmieg** [comment]
Thank you for your contact. The pmem/redis repository, which you are writing about, contains various prototypes of Redis adaptations to Persistent Memory. In the MemKeyDB organization, we went one step further: we have gathered various stakeholders, their requirements and focused on building a specific solution that will be a product rather than a prototype: it will support all the features of Redis and will be ported to its various versions. You are wellcome to contrubute to this community.

**Comment by vongosling** [comment]
Thanks, I would like to make some verification for MemKeyDB :-)
